import {useState,useEffect,useRef} from 'react';
import {useSearchParams} from 'react-router-dom';
import {Bot,Send,Trash2,Sparkles} from 'lucide-react';
import ReactMarkdown from 'react-markdown';
import api from '../api';
import LogBadge from '../components/LogBadge';
export default function Assistant(){
 const [params]=useSearchParams(),source=params.get('source');
 const [logs,setLogs]=useState([]),[input,setInput]=useState(''),[busy,setBusy]=useState(false),[mode,setMode]=useState('Mode is shown after your first investigation.');
 const [messages,setMessages]=useState(()=>{try{const saved=JSON.parse(sessionStorage.getItem('neurolog-investigation-chat'));return Array.isArray(saved)?saved:[];}catch{return [];}});
 const bottom=useRef(null);
 useEffect(()=>{sessionStorage.setItem('neurolog-investigation-chat',JSON.stringify(messages.slice(-50)));if(bottom.current){const box=bottom.current.parentElement;box.scrollTop=box.scrollHeight;}},[messages]);
 useEffect(()=>{let active=true;async function refresh(){try{const result=await api.get('/recent-logs?limit=300');if(active)setLogs(result.data);}catch{/* shared banner */}}refresh();const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer);};},[]);
 async function send(text=input){if(!text.trim()||busy)return;setMessages(m=>[...m,{sender:'user',text}]);setInput('');setBusy(true);try{const result=await api.post('/chat',{message:text});setMode(result.data.provider_warning||(result.data.mode==='groq'?'Groq language-model response':'Local evidence analysis · Rule-based'));setMessages(m=>[...m,{sender:'bot',text:result.data.reply}]);}catch{setMessages(m=>[...m,{sender:'bot',text:'Unable to load analysis. Check the API connection and try again.'}]);}finally{setBusy(false);}}
 const incidents=logs.filter(log=>log.severity_level<=3&&(!source||log.source===source)).slice(0,12);
 return <section><div className="page-heading"><div><span className="eyebrow">FROM SIGNAL TO UNDERSTANDING</span><h1>AI investigation</h1><p>{source?`Focused on ${source}.`:'Investigate incidents with evidence and practical next checks.'}</p></div><button className="primary" disabled={busy} onClick={()=>send(`Investigate recent errors ${source?'source:'+source:''} and suggest next checks`)}><Sparkles size={16}/>Investigate recent logs</button></div><div className="assistant-grid"><article className="panel"><div className="panel-heading"><div><h2>Incident inbox</h2><p>{incidents.length} recent error / critical records</p></div><span className="badge neutral">RECEIVED LOGS</span></div><div className="incident-feed">{incidents.map(log=><div className="incident-card" key={log._id}><LogBadge log={log}/><span style={{marginLeft:10,fontSize:11,color:'var(--text-muted)'}}>{log.source}</span><p>{log.message}</p><button className="secondary" disabled={busy} onClick={()=>send(`Investigate source:${log.source} and evidence #${log._id}: ${log.message}`)}>Investigate record #{log._id}</button></div>)}{!incidents.length&&<div className="empty-state">No recent error or critical records for this source.</div>}</div></article><article className="panel chat-panel"><div className="panel-heading"><h2><Bot size={17} style={{verticalAlign:'middle',marginRight:8}}/>Investigation notebook</h2><button className="icon-button" title="Clear conversation" aria-label="Clear conversation" disabled={busy} onClick={()=>setMessages([])}><Trash2 size={16}/></button></div><div className="chat-messages" aria-live="polite">{!messages.length&&<div className="empty-state"><Bot size={32}/><h2>Start with a question.</h2><p>Ask about errors, unusual messages, or a specific source. Findings reference received records.</p><button className="secondary" disabled={busy} onClick={()=>send('Explain recent anomalies and clustering results')}>Explain recent anomalies</button></div>}{messages.map((message,index)=><div key={index} className={`chat-message ${message.sender==='user'?'user':''}`}>{message.sender==='bot'?<ReactMarkdown>{message.text}</ReactMarkdown>:message.text}</div>)}{busy&&<p role="status">Investigating received evidence…</p>}<div ref={bottom}/></div><div className="mode-note">{mode} · Latest 300 records. Advisory only; no changes are executed.</div><form className="chat-compose" onSubmit={e=>{e.preventDefault();send();}}><input aria-label="Ask the assistant" placeholder="Ask about errors or use source:task-service…" value={input} onChange={e=>setInput(e.target.value)} disabled={busy}/><button className="primary" aria-label="Send message" disabled={busy||!input.trim()}><Send size={17}/></button></form></article></div></section>;
}
