import {useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,Plug,Activity,Search} from 'lucide-react';
import api from '../api';
export default function Applications({onSelect}){
 const [apps,setApps]=useState([]),[query,setQuery]=useState(''),[ready,setReady]=useState(false),[failed,setFailed]=useState(false),[clock,setClock]=useState(0);
 useEffect(()=>{let active=true;async function refresh(){try{const r=await api.get('/connections');if(active){setApps(r.data);setClock(Date.now());setReady(true);setFailed(false);}}catch{if(active)setFailed(true);}}refresh();const timer=setInterval(refresh,5000);return()=>{active=false;clearInterval(timer);};},[]);
 const filtered=apps.filter(a=>a.source.toLowerCase().includes(query.toLowerCase()));
 return <section className="applications-page"><div className="application-welcome"><span className="eyebrow">ONE APPLICATION AT A TIME</span><h1>Your applications.<br/><em>A clearer place to begin.</em></h1><p>Choose an application to explore its activity, understand its patterns, and investigate its signals.</p><Link className="button primary" to="/integrations"><Plug size={16}/>Connect another application</Link></div><div className="panel-heading application-list-heading"><div><h2>Connected applications</h2><p>{apps.length} sources have reported · refreshed every five seconds</p></div><label className="application-search"><Search size={16}/><input aria-label="Find application" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find an application…"/></label></div><div className="application-grid">{filtered.map(a=>{const age=clock-Date.parse(a.last_seen),recent=age<120000;return <button className="application-card panel" key={a.source} onClick={()=>onSelect(a.source)}><div className="application-card-top"><span className="application-symbol"><Activity size={24}/></span><span className={`badge ${recent?'success':'neutral'}`}>{recent?'Recently reporting':'No recent activity'}</span></div><h2>{a.source}</h2><p>Application intelligence workspace</p><div className="application-card-metrics"><div><strong>{a.records.toLocaleString()}</strong><span>received records</span></div><div><strong>{new Date(a.last_seen).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</strong><span>last received {new Date(a.last_seen).toLocaleDateString()}</span></div></div><div className="application-card-footer"><span>Open application</span><ArrowUpRight size={18}/></div></button>;})}</div>{!filtered.length&&<div className="panel empty-state"><Plug size={26}/><h2>{failed?'Cannot load applications':!ready?'Finding connected applications…':apps.length?'No matching applications':'Your first connection starts here'}</h2><p>{failed?'Check the API connection and try again.':apps.length?'Try another application name.':'Connect an application and send its first log to create a workspace.'}</p><Link className="button secondary" to="/integrations">Set up a connection</Link></div>}</section>;
}
