import {useState,useEffect,useCallback,useRef} from 'react';
import {ScatterChart,Scatter,XAxis,YAxis,Tooltip,ResponsiveContainer,Cell} from 'recharts';
import {Link} from 'react-router-dom';
import {Download,Pause,Play,X,Bell,ArrowUpRight} from 'lucide-react';
import api from '../api';
import Inspector from '../components/Inspector';
const colors={database:'#bf5973',auth:'#9a7025',upstream:'#8471bd',memory:'#aa559b',routine:'#6e9b8b',rate:'#997522'};
function csv(rows){const fields=['timestamp','source','trace_id','entity','message','category_label','risk_score','recurrence','generated'];const escape=v=>{let text=String(v??'');if(/^[=+@\-\t\r]/.test(text))text="'"+text;return '"'+text.replaceAll('"','""')+'"';};const blob=new Blob([[fields.join(','),...rows.map(r=>fields.map(f=>escape(r[f])).join(','))].join('\r\n')],{type:'text/csv;charset=utf-8'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='neurolog-investigations.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export default function Incidents(){
 const [tab,setTab]=useState('overview'),[data,setData]=useState(null),[rules,setRules]=useState([]),[space,setSpace]=useState(null),[selected,setSelected]=useState(null),[paused,setPaused]=useState(false),[search,setSearch]=useState(''),[risk,setRisk]=useState('all'),[category,setCategory]=useState('all'),[grouped,setGrouped]=useState(true),[persona,setPersona]=useState('sre'),[condition,setCondition]=useState('risk_gt_80'),[action,setAction]=useState('in_app'),[entity,setEntity]=useState(null),[toast,setToast]=useState(''),[loading,setLoading]=useState(false);
 const seen=useRef(new Set());
 const latestRecordId=data?.records[0]?._id;
 const refresh=useCallback(async()=>{setLoading(true);try{const result=await api.get('/intelligence');setData(result.data);const ruleResult=await api.get('/alert-rules');setRules(ruleResult.data);const fresh=result.data.alerts.filter(a=>!seen.current.has(a.id));result.data.alerts.forEach(a=>seen.current.add(a.id));if(fresh.length)setToast(`${fresh.length} alert rule matches. Open Alert rules for details.`);}catch{/* shared error */}finally{setLoading(false);}},[]);
 useEffect(()=>{if(!paused)refresh();const timer=setInterval(()=>{if(!paused)refresh();},5000);return()=>clearInterval(timer);},[paused,refresh]);
 useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),7000);return()=>clearTimeout(timer);},[toast]);
 useEffect(()=>{if(tab!=='space'&&!selected)return;let active=true;api.get('/vector-space'+(selected?`?record_id=${selected._id}`:'')).then(r=>{if(active)setSpace(r.data);}).catch(()=>{});return()=>{active=false;};},[selected,latestRecordId,tab]);
 useEffect(()=>{const key=e=>{if(['INPUT','TEXTAREA','SELECT','BUTTON'].includes(e.target.tagName)||e.ctrlKey||e.metaKey||e.altKey)return;if(e.code==='Space'){e.preventDefault();setPaused(p=>!p);}if(e.key.toLowerCase()==='n')refresh();if(e.key==='Escape'){setSelected(null);setEntity(null);}};document.addEventListener('keydown',key);return()=>document.removeEventListener('keydown',key);},[refresh]);
 const rows=(data?.records||[]).filter(r=>`${r.message} ${r.source} ${r.entity} ${r.trace_id||''}`.toLowerCase().includes(search.toLowerCase())&&(category==='all'||category===r.category)&&(risk==='all'||(risk==='high'?r.risk_score>=65:risk==='medium'?r.risk_score>=35&&r.risk_score<65:r.risk_score<35)));
 const display=grouped?rows.filter((r,i)=>rows.findIndex(other=>other.signature===r.signature)===i):rows;
 const current=selected?(data?.records.find(r=>r._id===selected._id)||selected):null;
 async function suppress(r){await api.post('/suppressions',{signature:r.signature,suppressed:!r.suppressed});setToast(r.suppressed?'Signature restored.':'Signature suppressed. Raw evidence is preserved; no model retraining.');refresh();}
 async function addRule(e){e.preventDefault();await api.post('/alert-rules',{condition,action});refresh();}
 const explanation=current?{record_id:current._id,source:current.source,entity:current.entity,generated:current.generated,risk_score:current.risk_score,factors:current.factors,recurrence:current.recurrence,next_step:current.next_step,root_cause:'Unconfirmed'}:null;
 return <section><div className="page-heading"><div><span className="eyebrow">EVIDENCE, IN CONTEXT</span><h1>Connect the signals</h1><p>Understand repeated activity, review the evidence, and decide what matters.</p></div><div className="workbench-actions"><button onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>} {paused?'Resume':'Pause'}</button><button disabled={loading} onClick={refresh}>{loading?'Refreshing…':'Refresh once'}</button></div></div>
 {toast&&<div className="notice" role="status"><Bell size={16}/>{toast}<button onClick={()=>setToast('')}>Dismiss</button></div>}
 <div className="stats-grid">{[['Raw error alerts',data?.metrics.raw_alerts],['Grouped incidents',data?.metrics.grouped_incidents],['Grouping reduction',`${data?.metrics.reduction_percent??0}%`],['Analysis time',`${data?.metrics.analysis_ms??0} ms`]].map(([label,value])=><article className="panel stat-card" key={label}><div>{label}</div><strong>{value??'—'}</strong><small>Measured over the latest 300 records</small></article>)}</div>
 <div className="workspace-tabs" aria-label="Investigation views">{[['overview','Incident overview'],['ledger','Evidence ledger'],['space','Message space'],['rules','Alert rules']].map(([value,label])=><button key={value} aria-pressed={tab===value} onClick={()=>setTab(value)}>{label}</button>)}</div><p className="method-note">Severity, five-minute recurrence, and stored outliers inform risk. Scores support review; they do not establish a root cause.</p>
 <div className={`workbench-tab-panel ${tab==='overview'?'visible':''}`}><article className="panel"><div className="panel-heading"><h2>System insights & entity watchlist</h2></div>{data?.insights.map((ins,i)=><div className="incident-card" key={i}><span className="badge warning">{ins.generated?'Generated scenario':'Actual activity'}</span><h3>{ins.title}</h3><p>{ins.count} events · {ins.sources.join(', ')}</p><p>{ins.description}</p><small>Evidence: {ins.evidence.join(', ')}</small></div>)}{!data?.insights.length&&<div className="empty-state">No correlated error pattern in the current five-minute window.</div>}{data?.incidents.slice(0,6).map(g=><div className="source-row" key={g.id}><button className="text-link" onClick={()=>setEntity(g.entity)}>{g.entity}</button><p>{g.title} · {g.count} events · risk {g.risk_score}</p></div>)}</article></div><div className={`workbench-tab-panel ${tab==='rules'?'visible':''}`}><article className="panel"><div className="panel-heading"><h2>Alert rules</h2><span className="badge purple">{rules.length} active</span></div><form className="rule-form" onSubmit={addRule}><label>Condition<select value={condition} onChange={e=>setCondition(e.target.value)}><option value="risk_gt_80">Risk above 80</option><option value="database_error">Database warning / error</option><option value="auth_repeated">Repeated authentication rejection</option></select></label><label>Action<select value={action} onChange={e=>setAction(e.target.value)}><option value="in_app">In-app notification</option><option value="pagerduty">PagerDuty payload preview</option><option value="slack">Slack payload preview</option><option value="webhook">Webhook payload preview</option></select></label><button className="primary">Add rule</button><p>External actions produce reviewable payloads. No message is sent to another service.</p></form>{rules.map(r=><div className="rule-row" key={r.id}><span>{r.condition} → {r.action}</span><button aria-label={`Remove rule ${r.id}`} onClick={async()=>{await api.delete(`/alert-rules/${r.id}`);refresh();}}>Remove</button></div>)}<details className="payload-details"><summary>Matched alert payloads ({data?.alerts.length||0})</summary><pre>{JSON.stringify(data?.alerts||[],null,2)}</pre></details></article></div>
 <div className={`workbench-tab-panel ${tab==='space'?'visible':''}`}><article className="panel pattern-panel"><div className="panel-heading"><div><h2>Message space & nearest neighbors</h2><p>Real TF-IDF vectors projected into two dimensions. Select a point to inspect.</p></div><span className="badge neutral">{space?.dimensions??0} terms</span></div><div className="embedding-layout"><div className="chart-container" aria-label="TF-IDF message projection"><ResponsiveContainer width="100%" height="100%"><ScatterChart><XAxis dataKey="x" type="number" name="Projection 1" hide/><YAxis dataKey="y" type="number" name="Projection 2" hide/><Tooltip content={({active,payload})=>active&&payload?.length?<div className="vector-tooltip">#{payload[0].payload.id} · {payload[0].payload.category}<p>{payload[0].payload.message}</p></div>:null}/><Scatter data={space?.points||[]} onClick={point=>setSelected(data?.records.find(r=>r._id===point.id))}>{space?.points.map(p=><Cell key={p.id} fill={colors[p.category]||'#999'} />)}</Scatter></ScatterChart></ResponsiveContainer></div><div className="neighbor-list"><h3>Nearest messages</h3>{space?.neighbors.map(n=><button key={n.id} onClick={()=>setSelected(data?.records.find(r=>r._id===n.id))}><span>#{n.id} · cosine {n.similarity}</span><small>{n.message}</small></button>)}<p>{space?.method}</p></div></div><div className="vector-record-picker"><label>Select record without the chart<select value={current?._id||space?.selected_id||''} onChange={e=>setSelected(data?.records.find(r=>r._id===Number(e.target.value)))}>{space?.points.map(p=><option value={p.id} key={p.id}>#{p.id} · {p.source} · {p.category}</option>)}</select></label></div></article></div>
 <div className={`workbench-tab-panel ${tab==='ledger'?'visible':''}`}><article className="panel"><div className="panel-heading"><h2>Investigation ledger</h2><button onClick={()=>csv(rows)}><Download size={16}/>Export CSV</button></div><div className="filterbar"><input aria-label="Search investigation ledger" placeholder="Message, trace, source or entity…" value={search} onChange={e=>setSearch(e.target.value)}/><select aria-label="Category filter" value={category} onChange={e=>setCategory(e.target.value)}><option value="all">All categories</option>{[...new Set(data?.records.map(r=>r.category)||[])].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Risk filter" value={risk} onChange={e=>setRisk(e.target.value)}><option value="all">Any risk</option><option value="high">High ≥65</option><option value="medium">Medium 35–64</option><option value="low">Low &lt;35</option></select><button aria-pressed={grouped} onClick={()=>setGrouped(!grouped)}>{grouped?'Grouped view':'Raw view'}</button></div><div className="table-meta">{rows.length} matching records · {display.length} displayed · {paused?'Paused':'Live'}</div><div className="table-scroll"><table className="log-table"><thead><tr><th>Time / trace</th><th>Entity / source</th><th>Message</th><th>Category</th><th>Risk</th><th>Inspect</th></tr></thead><tbody>{display.map(r=><tr key={r._id}><td>{new Date(r.timestamp).toLocaleTimeString()}<br/><small>{r.trace_id||'No trace supplied'}</small></td><td><button className="text-link" onClick={()=>setEntity(r.entity)}>{r.entity}</button><br/>{r.source}</td><td><span className="message-preview">{r.message}</span>{grouped&&<small>{rows.filter(x=>x.signature===r.signature).length} similar records</small>}{r.suppressed&&<span className="badge neutral">Suppressed</span>}</td><td>{r.category_label}</td><td><span className={`badge ${r.risk_score>=65?'danger':r.risk_score>=35?'warning':'neutral'}`}>{r.risk_score}</span></td><td><button aria-label={`Replay record ${r._id}`} onClick={()=>setSelected(r)}><ArrowUpRight size={16}/></button></td></tr>)}</tbody></table></div>{!display.length&&<div className="empty-state">{data?'No records match these filters.':'Loading investigation evidence…'}</div>}</article></div>
 {current&&<Inspector label="Investigation replay" onClose={()=>setSelected(null)}><div className="panel-heading"><h2>Record #{current._id}</h2><button aria-label="Close replay" onClick={()=>setSelected(null)}><X size={16}/></button></div><p>{current.generated?'Generated scenario':'Actual activity'} · {current.source}</p><pre>{current.message}</pre><h3>Processing evidence</h3><ol className="pipeline-evidence"><li>Ingested: {new Date(current.timestamp).toLocaleString()} · {current.trace_id||'No trace supplied'}</li><li>Vectorized: {space?.tokens.map(t=>`${t.term} (${t.weight})`).join(', ')||'No usable terms'}</li><li>Stored cluster: {current.cluster_id??'Not run'} · category: {current.category_label}</li><li>Risk: {current.risk_score}/100{current.factors.map(f=><p key={f.name}>{f.name}: {f.points>0?'+':''}{f.points}</p>)}</li><li>Explanation: {current.recurrence} matching category / entity events in five minutes. Root cause remains unconfirmed.</li><li>Published to the investigation ledger.</li></ol><label>Explanation format<select value={persona} onChange={e=>setPersona(e.target.value)}><option value="sre">SRE incident summary</option><option value="junior">Beginner explanation</option><option value="json">Structured JSON</option></select></label>{persona==='json'?<pre>{JSON.stringify(explanation,null,2)}</pre>:<p>{persona==='junior'?'This event gets review points from its severity, repeated activity, and any stored outlier flag. ':`${current.category_label}; risk ${current.risk_score}. `}{current.next_step}</p>}<button onClick={()=>suppress(current)}>{current.suppressed?'Restore signature':'Mark false positive / suppress'}</button><p>Suppression is reversible and preserves raw logs.</p><Link className="button primary" to={`/assistant?source=${encodeURIComponent(current.source)}`}>Ask AI about this source</Link></Inspector>}
 {entity&&<Inspector label="Entity timeline" onClose={()=>setEntity(null)}><div className="panel-heading"><h2>{entity}</h2><button aria-label="Close entity timeline" onClick={()=>setEntity(null)}><X size={16}/></button></div><p>Cross-service history in the latest 300 records. Source is used when no entity ID is supplied.</p>{data?.records.filter(r=>r.entity===entity).map(r=><div className="incident-card" key={r._id}><strong>#{r._id} · {r.source}</strong><p>{new Date(r.timestamp).toLocaleString()} · {r.trace_id||'No trace'}</p><p>{r.message}</p></div>)}</Inspector>}
 </section>;
}
