import {useState,useEffect} from 'react';
import {Link,useSearchParams} from 'react-router-dom';
import {Search, Pause, Play, X, ArrowUpRight} from 'lucide-react';
import api from '../api';
import LogBadge from '../components/LogBadge';
export default function LogExplorer(){
 const [params]=useSearchParams();
 const [logs,setLogs]=useState([]),[search,setSearch]=useState(''),[severity,setSeverity]=useState(params.get('severity')||'all'),[source,setSource]=useState('all'),[kind,setKind]=useState('all'),[paused,setPaused]=useState(false),[selected,setSelected]=useState(null),[loaded,setLoaded]=useState(false),[updated,setUpdated]=useState(null);
 useEffect(()=>{let active=true;async function refresh(){try{const result=await api.get('/recent-logs?limit=300');if(active){setLogs(result.data);setUpdated(new Date());setLoaded(true);}}catch{/* shared banner */}}if(!paused)refresh();const timer=setInterval(()=>{if(!paused)refresh();},3000);return()=>{active=false;clearInterval(timer);};},[paused]);
 const filtered=logs.filter(log=>(severity==='all'||(severity==='errors'?log.severity_level<=3:severity==='warning'?log.severity_level===4:log.severity_level>=5))&&(source==='all'||source===log.source)&&(kind==='all'||(kind==='generated')===log.message.startsWith('[GENERATED]'))&&`${log.message} ${log.source}`.toLowerCase().includes(search.toLowerCase()));
 return <section><div className="page-heading"><div><span className="eyebrow">EXPLORE & INVESTIGATE</span><h1>Log workspace</h1><p>Find the signal in your application activity.</p></div><button className="secondary" onClick={()=>setPaused(!paused)}>{paused?<Play size={16}/>:<Pause size={16}/>} {paused?'Resume updates':'Pause updates'}</button></div>
 <div className="panel"><div className="filterbar"><label className="search-field"><Search size={18}/><input aria-label="Search logs" placeholder="Search messages or services…" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filter severity" value={severity} onChange={e=>setSeverity(e.target.value)}><option value="all">All severities</option><option value="errors">Errors & critical</option><option value="warning">Warnings</option><option value="routine">Routine activity</option></select><select aria-label="Filter source" value={source} onChange={e=>setSource(e.target.value)}><option value="all">All sources</option>{[...new Set(logs.map(l=>l.source))].map(s=><option key={s}>{s}</option>)}</select><select aria-label="Filter origin" value={kind} onChange={e=>setKind(e.target.value)}><option value="all">All origins</option><option value="actual">Actual activity</option><option value="generated">Generated scenarios</option></select></div><div className="table-meta"><span>{filtered.length} matching / {logs.length} recent records</span><span><span className={`status-dot ${paused?'paused':''}`}/>{paused?'Updates paused':updated?`Updated ${updated.toLocaleTimeString()}`:'Connecting…'}</span></div>
 <div className="table-scroll"><table className="log-table"><thead><tr><th>Time</th><th>Severity</th><th>Source</th><th>Message</th><th><span className="sr-only">Details</span></th></tr></thead><tbody>{filtered.map(log=><tr key={log._id} className={selected?._id===log._id?'selected':''}><td className="time-cell">{new Date(log.timestamp).toLocaleTimeString()}</td><td><LogBadge log={log}/></td><td>{log.source}</td><td className="message-cell"><span className="message-preview">{log.message}</span>{log.ml_anomaly? <span className="badge purple">Outlier</span>:null}</td><td><button className="icon-button" aria-label={`Inspect log ${log._id}`} onClick={()=>setSelected(log)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>{!filtered.length&&<div className="empty-state">{loaded?'No matching logs. Adjust your filters or generate activity in the Python app.':'Loading received records…'}<button className="secondary" onClick={()=>{setSearch('');setSeverity('all');setSource('all');setKind('all');}}>Reset filters</button></div>}</div>
 {selected&&<aside className="detail-panel" aria-label="Log details"><div className="panel-heading"><h2>Record #{selected._id}</h2><button className="icon-button" aria-label="Close log details" onClick={()=>setSelected(null)}><X size={18}/></button></div><LogBadge log={selected}/><dl><dt>Source</dt><dd>{selected.source}</dd><dt>Received</dt><dd>{new Date(selected.timestamp).toLocaleString()}</dd><dt>Origin</dt><dd>{selected.message.startsWith('[GENERATED]')?'Generated scenario':'Application activity'}</dd><dt>Analysis</dt><dd>{selected.cluster_id===null?'Not analyzed':`Cluster ${selected.cluster_id}${selected.ml_anomaly?' · Outlier':''}`}</dd></dl><pre>{selected.message}</pre><Link className="button primary" to={`/assistant?source=${encodeURIComponent(selected.source)}`}>Investigate source <ArrowUpRight size={16}/></Link></aside>}
 </section>;
}
