import {createElement} from 'react';
import {useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {Activity,AlertTriangle,Layers3,Radio,ArrowUpRight} from 'lucide-react';
import {ResponsiveContainer,BarChart,Bar,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import api from '../api';
import LogBadge from '../components/LogBadge';
export default function Dashboard(){
 const [logs,setLogs]=useState([]),[ready,setReady]=useState(false),[online,setOnline]=useState(false);
 useEffect(()=>{let active=true;async function refresh(){try{const res=await api.get('/recent-logs?limit=300');if(active){setLogs(res.data);setOnline(true);setReady(true);}}catch{if(active)setOnline(false);}}refresh();const timer=setInterval(refresh,3000);return()=>{active=false;clearInterval(timer);};},[]);
 const errors=logs.filter(l=>l.severity_level<=3),outliers=logs.filter(l=>l.ml_anomaly),sources=[...new Set(logs.map(l=>l.source))],generated=logs.filter(l=>l.message.startsWith('[GENERATED]')).length;
 const minutes=new Map();[...logs].reverse().forEach(log=>{const time=new Date(log.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const bucket=minutes.get(time)||{time,routine:0,errors:0};bucket[log.severity_level<=3?'errors':'routine']++;minutes.set(time,bucket);});
 const stats=[['Recent records',logs.length,Activity,'Latest 300 received entries'],['Errors & critical',errors.length,AlertTriangle,'Includes labeled generated scenarios'],['ML outliers',outliers.length,Layers3,'From the last analysis run'],['Reporting sources',sources.length,Radio,'Sources in this record window']];
 return <section><div className="page-heading"><div><span className="eyebrow">YOUR OPERATIONS, AT A GLANCE</span><h1>Monitoring overview</h1><p>A clear view of incoming activity and what needs a closer look.</p></div><span className={`badge ${online?'success':'warning'}`}><span className={`status-dot ${online?'':'paused'}`}/>{online?'API connected':'Connecting to API'}</span></div><div className="stats-grid">{stats.map(([label,value,Icon,hint])=><article className="panel stat-card" key={label}><div><span>{label}</span>{createElement(Icon,{size:18})}</div><strong>{ready?value:'—'}</strong><small>{hint}</small></article>)}</div>
 <div className="overview-grid"><article className="panel"><div className="panel-heading"><div><h2>Incoming activity</h2><p>Records per minute in the current window</p></div><span className="chart-legend"><i/>Routine <i className="red"/>Errors</span></div><div className="chart-container" role="img" aria-label={`Incoming activity: ${logs.length-errors.length} routine records and ${errors.length} error records`}><ResponsiveContainer width="100%" height="100%"><BarChart data={[...minutes.values()].slice(-20)}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="time" stroke="var(--text-muted)" tickLine={false} axisLine={false} fontSize={11}/><YAxis stroke="var(--text-muted)" tickLine={false} axisLine={false} width={30} allowDecimals={false} fontSize={11}/><Tooltip contentStyle={{background:'var(--surface)',border:'1px solid var(--border)',borderRadius:8}}/><Bar dataKey="routine" name="Routine" stackId="a" fill="#6489eb"/><Bar dataKey="errors" name="Errors" stackId="a" fill="#d96c75" radius={[3,3,0,0]}/></BarChart></ResponsiveContainer></div></article><article className="panel"><div className="panel-heading"><h2>Source activity</h2><Radio size={18}/></div>{sources.length?sources.map(source=>{const count=logs.filter(l=>l.source===source).length;return <div className="source-row" key={source}><div><strong>{source}</strong><span>{count} records</span></div><div className="progress-track"><div style={{width:`${count/Math.max(logs.length,1)*100}%`}}/></div></div>}):<div className="empty-state">Waiting for your first source.</div>}<div className="context-note"><strong>{generated} generated entries</strong><p>Scenario logs are labeled. They do not establish a real service outage.</p></div><a className="text-link" href={import.meta.env.VITE_SOURCE_URL || "http://127.0.0.1:8000"} target="_blank" rel="noreferrer">Manage Python log source <ArrowUpRight size={15}/></a></article></div>
 <article className="panel"><div className="panel-heading"><div><h2>Needs attention</h2><p>Recent error and critical records</p></div><Link className="text-link" to="/explorer?severity=errors">Open log workspace <ArrowUpRight size={16}/></Link></div>{errors.slice(0,5).map(log=><Link className="attention-row" key={log._id} to={`/assistant?source=${encodeURIComponent(log.source)}`}><LogBadge log={log}/><div><strong>{log.source}</strong><p>{log.message}</p></div><span>{new Date(log.timestamp).toLocaleTimeString()}</span><ArrowUpRight size={17}/></Link>)}{!errors.length&&<div className="empty-state">No error or critical records in this window.</div>}</article></section>;
}
