import {useEffect,useState,createElement} from 'react';
import {Link} from 'react-router-dom';
import {Activity,AlertCircle,Layers3,Radio,ArrowUpRight,Search,Sparkles,ArrowRight} from 'lucide-react';
import {ResponsiveContainer,AreaChart,Area,XAxis,YAxis,Tooltip,CartesianGrid} from 'recharts';
import api from '../api';
import PatternPanel from '../components/PatternPanel';
import LogBadge from '../components/LogBadge';
import ScenarioControl from '../components/ScenarioControl';
export default function Dashboard(){
 const [logs,setLogs]=useState([]),[ready,setReady]=useState(false),[online,setOnline]=useState(false);
 useEffect(()=>{let active=true;async function refresh(){try{const res=await api.get('/recent-logs?limit=300');if(active){setLogs(res.data);setOnline(true);setReady(true);}}catch{if(active)setOnline(false);}}refresh();const timer=setInterval(refresh,3000);return()=>{active=false;clearInterval(timer);};},[]);
 const errors=logs.filter(l=>l.severity_level<=3),outliers=logs.filter(l=>l.ml_anomaly),sources=[...new Set(logs.map(l=>l.source))],generated=logs.filter(l=>l.message.startsWith('[GENERATED]')).length;
 const minutes=new Map();[...logs].reverse().forEach(log=>{const time=new Date(log.timestamp).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'});const bucket=minutes.get(time)||{time,routine:0,errors:0};bucket[log.severity_level<=3?'errors':'routine']++;minutes.set(time,bucket);});
 const stats=[['Records received',logs.length,Activity,'Latest 300 entries'],['Errors to review',errors.length,AlertCircle,'Error and critical records'],['Clustering outliers',outliers.length,Layers3,'Last completed analysis'],['Connected sources',sources.length,Radio,'Reporting in this window']];
 return <section className="overview-page"><div className="overview-intro"><div className="overview-greeting"><span className="eyebrow">YOUR OBSERVABILITY WORKSPACE</span><div className="signal-row"><span className={`badge ${online?'success':'warning'}`}><span className={`status-dot ${online?'':'paused'}`}/>{online?'Receiving activity':'Connecting'}</span><small>{new Date().toLocaleDateString(undefined,{month:'long',day:'numeric',year:'numeric'})}</small></div><h1>A clearer picture.<br/><em>A calmer workspace.</em></h1><p>Follow your application’s activity, understand what repeats, and bring the right evidence into every investigation.</p><div className="overview-tools"><Link className="button primary" to="/explorer"><Search size={15}/>Explore logs</Link><Link className="button secondary" to="/assistant"><Sparkles size={15}/>Ask your assistant</Link></div></div><article className="overview-signal"><span className="eyebrow">YOUR NEXT STEP</span><h2>{!ready?'Connecting the dots…':errors.length?'Some signals need a closer look.':'Make sense of what’s coming in.'}</h2><p>{errors.length?`${errors.length} error or critical records in your current window. Review them with their surrounding activity.`:'Start with the log stream, then explore repeated patterns and unusual messages.'}</p><Link to={errors.length?'/incidents':'/analysis'}>{errors.length?'Open incident workbench':'Explore message patterns'}<ArrowRight size={15}/></Link><div className="signal-orbit" aria-hidden="true"/></article></div><div className="stats-grid">{stats.map(([label,value,Icon,hint])=><article className="panel stat-card" key={label}><div><span>{label}</span>{createElement(Icon,{size:16,'aria-hidden':true})}</div><strong>{ready?value:'—'}</strong><small>{hint}</small></article>)}</div>
 <div className="overview-grid"><article className="panel"><div className="panel-heading"><div><h2>The activity stream</h2><p>Received records per minute · current window</p></div><span className="chart-legend"><i/>Routine <i className="red"/>Errors</span></div><div className="chart-container" role="img" aria-label={`${logs.length-errors.length} routine records and ${errors.length} error records`}><ResponsiveContainer width="100%" height="100%"><AreaChart data={[...minutes.values()].slice(-20)} margin={{top:15,right:10,left:0,bottom:0}}><defs><linearGradient id="routineFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--chart-routine)" stopOpacity={.2}/><stop offset="100%" stopColor="var(--chart-routine)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)" strokeDasharray="3 5"/><XAxis dataKey="time" stroke="var(--text-muted)" tickLine={false} axisLine={false} fontSize={10} dy={8}/><YAxis stroke="var(--text-muted)" tickLine={false} axisLine={false} width={28} allowDecimals={false} fontSize={10}/><Tooltip contentStyle={{background:'var(--surface)',border:'1px solid var(--border)',borderRadius:9,fontSize:11}}/><Area type="monotone" dataKey="routine" name="Routine" stroke="var(--chart-routine)" fill="url(#routineFill)" strokeWidth={2}/><Area type="monotone" dataKey="errors" name="Errors" stroke="var(--chart-error)" fill="var(--chart-error)" fillOpacity={.06} strokeWidth={2}/></AreaChart></ResponsiveContainer></div></article><article className="panel"><div className="panel-heading"><div><h2>Your connected sources</h2><p>Where the activity comes from</p></div><Radio size={17} color="var(--accent)"/></div>{sources.length?sources.map(source=>{const count=logs.filter(l=>l.source===source).length;return <div className="source-row" key={source}><div><strong>{source}</strong><span>{count} records</span></div><div className="progress-track"><div style={{width:`${count/Math.max(logs.length,1)*100}%`}}/></div></div>}):<div className="empty-state">No source has reported yet.</div>}<div className="context-note"><strong>{generated} scenario records</strong><p>Generated events are labeled and kept distinguishable from actual application activity.</p></div><a className="text-link" href={import.meta.env.VITE_SOURCE_URL||'http://127.0.0.1:8000'} target="_blank" rel="noreferrer">Manage log source<ArrowUpRight size={14}/></a></article></div><ScenarioControl/><PatternPanel/>
 <div className="overview-footgrid"><article className="panel"><div className="panel-heading"><div><h2>Worth a closer look</h2><p>Most recent error and critical records</p></div><Link className="text-link" to="/explorer?severity=errors">View all<ArrowUpRight size={14}/></Link></div>{errors.slice(0,4).map(log=><Link className="attention-row" key={log._id} to={`/assistant?source=${encodeURIComponent(log.source)}`}><LogBadge log={log}/><div><strong>{log.source}</strong><p>{log.message}</p></div><ArrowUpRight size={14}/></Link>)}{!errors.length&&<div className="empty-state"><Activity size={24}/><h2>No errors in this window.</h2><p>Keep an eye on incoming activity as your sources report.</p></div>}</article><article className="panel"><div className="panel-heading"><div><h2>A few ways forward</h2><p>Choose a starting point for your investigation</p></div></div><div className="quick-paths">{[['/explorer',Search,'Explore the raw evidence','Search and filter every received event.'],['/incidents',Layers3,'Connect the signals','Review recurrence, risk factors, and entity history.'],['/assistant',Sparkles,'Ask a focused question','Bring log evidence into a conversation.']].map(([url,Icon,title,description])=><Link className="quick-path" to={url} key={url}><span>{createElement(Icon,{size:16})}</span><div><strong>{title}</strong><p>{description}</p></div><ArrowUpRight size={14}/></Link>)}</div></article></div></section>;
}
