import {useState,useEffect,useCallback} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,Layers3,Sparkles,ScanLine} from 'lucide-react';
import api from '../api';
import LogBadge from '../components/LogBadge';
export default function Analysis({tab,paused=false}){
 const [logs,setLogs]=useState([]),[busy,setBusy]=useState(false),[notice,setNotice]=useState('');
 const refresh=useCallback(async()=>{try{const result=await api.get('/recent-logs?limit=300');setLogs(result.data);}catch{/* shared error */}},[]);
 useEffect(()=>{if(!paused)refresh();const timer=setInterval(()=>{if(!paused)refresh();},5000);window.addEventListener('neurolog-analysis',refresh);return()=>{clearInterval(timer);window.removeEventListener('neurolog-analysis',refresh);};},[refresh,paused]);
 async function run(){setBusy(true);try{setNotice((await api.post('/run-ml')).data.status);await refresh();}catch{/* shared error */}finally{setBusy(false);}}
 const analyzed=logs.filter(l=>l.cluster_id!==null),outliers=logs.filter(l=>l.ml_anomaly),groups=[...new Set(analyzed.filter(l=>l.cluster_id!==-1).map(l=>l.cluster_id))];
 return <div><div className="panel-heading"><div><h2>{tab==='clusters'?'Similar messages, together':'Unusual messages to review'}</h2><p>{analyzed.length} analyzed records · {groups.length} clusters · {outliers.length} outliers</p></div><button className="primary" onClick={run} disabled={busy}><Sparkles size={15}/>{busy?'Analyzing…':'Run clustering'}</button></div>{notice&&<div className="notice" role="status">{notice}<button onClick={()=>setNotice('')}>Dismiss</button></div>}{tab==='clusters'&&<div className="cluster-grid">{groups.map(id=>{const entries=analyzed.filter(l=>l.cluster_id===id);return <article className="panel cluster-card" key={id}><div className="cluster-card-top"><span className="cluster-symbol"><Layers3 size={19}/></span><span className="badge neutral">{entries.length} records</span></div><h2>Message group {id}</h2><p className="cluster-example">{entries[0].message}</p><div className="cluster-sources">{[...new Set(entries.map(l=>l.source))].map(source=><span className="badge neutral" key={source}>{source}</span>)}</div><Link className="text-link" to={`/explorer?q=${encodeURIComponent(entries[0].source)}`}>Explore the source<ArrowUpRight size={13}/></Link></article>;})}{!groups.length&&<article className="panel empty-state"><Layers3 size={25}/><h2>No message groups yet</h2><p>Run clustering on at least five records to group similar messages.</p><button onClick={run} disabled={busy}>Analyze the current window</button></article>}</div>}{tab==='outliers'&&<article className="panel"><div className="panel-heading"><div><h2>Outlier review queue</h2><p>Messages isolated by the last TF-IDF / DBSCAN run</p></div><span className="badge purple">{outliers.length} records</span></div>{outliers.map(log=><div className="incident-card" key={log._id}><div className="outlier-heading"><LogBadge log={log}/><strong>{log.source}</strong><small>#{log._id}</small></div><p className="cluster-example">{log.message}</p><Link className="text-link" to={`/assistant?source=${encodeURIComponent(log.source)}`}>Investigate with context<ArrowUpRight size={13}/></Link></div>)}{!outliers.length&&<div className="empty-state"><ScanLine size={25}/><h2>No isolated messages to review</h2><p>Clustering results update when you run analysis.</p></div>}</article>}<p className="analysis-method">Repeated-pattern detection updates automatically. Clustering is refreshed on request. Both describe message structure; neither confirms a service failure.</p></div>;
}
