import {useState,useEffect} from 'react';
import {Link} from 'react-router-dom';
import {ArrowUpRight,ScanLine} from 'lucide-react';
import api from '../api';
export default function PatternPanel({paused=false}){
 const [data,setData]=useState(null),[failed,setFailed]=useState(false);
 useEffect(()=>{let active=true;async function refresh(){try{const res=await api.get('/patterns');if(active){setData(res.data);setFailed(false);}}catch{if(active)setFailed(true);}}refresh();const timer=setInterval(()=>{if(!paused)refresh();},5000);return()=>{active=false;clearInterval(timer);};},[paused]);
 return <article className="panel pattern-panel"><div className="panel-heading"><div><span className="eyebrow">AUTOMATIC DISCOVERY</span><h2>Patterns in your stream</h2><p>Repeated messages, grouped across changing IDs and measurements.</p></div><ScanLine size={22}/></div><div className="pattern-summary"><strong>{data?.patterns.length??'—'}</strong><span>recurring patterns</span><span className="badge purple">{data?.repeated_records??0} matching records</span></div><div className="pattern-grid">{data?.patterns.slice(0,8).map((p,i)=><div className="pattern-tile" key={i}><div className="pattern-title"><span className={`badge ${['ERROR','CRITICAL'].includes(p.severity)?'danger':p.severity==='WARNING'?'warning':'neutral'}`}>{p.severity}</span><span>{p.count} occurrences</span></div><h3>{p.name||p.template}</h3><p>{p.source} · {p.generated?'Generated scenario':'Actual activity'} · {p.share_percent}% of window</p><div className="progress-track"><div style={{width:`${p.share_percent}%`}}/></div><details><summary>Message & investigation</summary><p>{p.template}</p><p>Record IDs: {p.evidence.join(', ')}. First seen {new Date(p.first_seen).toLocaleTimeString()}, latest {new Date(p.last_seen).toLocaleTimeString()}.</p><p>{p.next_step}</p></details><Link className="text-link" to={`/assistant?source=${encodeURIComponent(p.source)}`}>Investigate <ArrowUpRight size={15}/></Link></div>)}</div>{!data?.patterns.length&&<div className="empty-state">{failed?'Pattern analysis is unavailable. Retry when the API reconnects.':data?'No repeated messages yet. Start the Python generator or send more logs.':'Looking for recurring activity…'}</div>}<p className="pattern-footnote">{paused?'Automatic updates paused.':'Updates every five seconds from the latest 300 records.'} Recurrence describes log behavior; it does not confirm a root cause.</p></article>;
}
